apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: meryemberra/swe304-app
          ports:
            - containerPort: 8088
          env:
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: swe304
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: '12345'
